export type Category =
  | "domestic"
  | "global"
  | "policy"
  | "rnd"
  | "insight"
  | "guide";

export interface Article {
  id: number;
  title: string;
  summary: string;
  category: Category;
  categoryLabel: string;
  date: string;
  country?: string;
  link?: string;
  image?: string;
  source?: string;
  featured?: boolean;
}

export const CATEGORIES: { slug: Category; label: string; labelEn: string }[] = [
  { slug: "domestic", label: "국내", labelEn: "Domestic" },
  { slug: "global", label: "글로벌", labelEn: "Global" },
  { slug: "policy", label: "정책·규제", labelEn: "Policy" },
  { slug: "rnd", label: "R&D·기술", labelEn: "R&D" },
  { slug: "insight", label: "인사이트", labelEn: "Insight" },
  { slug: "guide", label: "가이드", labelEn: "Guide" },
];

// ── 2026-05-11 주간 뉴스 ──────────────────────────────────────────────────

const ARTICLES_20260511: Article[] = [
  // 정책·규제
  {
    id: 1,
    title: "이스라엘 보건부, 흡연 의료대마 3년 내 단계적 폐지 권고 — 5/10 보건부장관 동결",
    summary: "이스라엘 보건부 위원회가 흡연 의료대마를 3년 내 단계적으로 폐지하도록 권고했으나, 보건부장관이 5월 10일 해당 권고를 동결 조치했다. 산업계 충격과 환자 단체 반발이 동시에 나타나고 있다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-10",
    country: "이스라엘",
    link: "https://mjbizdaily.com/news/should-medical-cannabis-be-smoked-israel-debates-removing-smokeable-flower/615816/",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    featured: true,
  },
  {
    id: 2,
    title: "Trump '2026 국가 마약 통제 전략' 발표 — Delta-8/HHC 등 향정 헴프 Schedule I 지정 포함",
    summary: "트럼프 행정부가 발표한 2026 국가 마약 통제 전략에 Delta-8 THC, HHC 등 향정신성 헴프 파생물을 Schedule I로 지정하는 내용이 포함되어 헴프 산업계에 파장을 일으키고 있다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-04",
    country: "미국",
    link: "https://www.cannabisbusinesstimes.com/hemp/news/15824298/trump-administration-claims-new-legal-authority-to-dismantle-intoxicating-hemp-products",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
  },
  {
    id: 3,
    title: "미국 하원, 2026 Farm Bill 통과 — 향정 헴프 금지 유지·Sen. Rand Paul 수정안 부결",
    summary: "미국 하원이 2026 Farm Bill을 통과시켰다. Delta-8 등 향정신성 헴프 파생물 금지 조항이 유지됐으며, Rand Paul 상원의원의 규제 완화 수정안은 부결됐다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-05",
    country: "미국",
    link: "https://www.cannabisbusinesstimes.com/hemp/news/15823852/s-house-passes-2026-farm-bill-intoxicating-hemp-product-ban-remains",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80",
  },
  {
    id: 4,
    title: "텍사스 법원: 헴프 머천트, 여름까지 THCA 플라워 판매 계속 가능 — 4일 판결",
    summary: "텍사스 법원이 헴프 판매업체들이 적어도 여름까지 THCA 플라워 판매를 계속할 수 있다고 판결했다. 주 정부의 금지 시행이 일시 중단된 상태다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-04",
    country: "미국",
    link: "https://www.cannabisbusinesstimes.com/us-states/texas/news/15822051/thca-flower-sales-resume-in-texas-after-judge-grants-tro",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
  },
  {
    id: 5,
    title: "NLRB: 대마 사전 롤·데이터 입력은 농업 노동 아닌 가공 노동 — 5/5 판결",
    summary: "미국 노동관계위원회(NLRB)가 대마 사전 롤 제조 및 데이터 입력 작업을 농업 노동이 아닌 가공 노동으로 분류한다고 판결했다. 이에 따라 해당 노동자들에게 노동법 보호가 적용된다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-05",
    country: "미국",
    link: "https://mjbizdaily.com/news/feds-hand-loss-to-missouri-cannabis-operator-in-labor-fight/615835/",
    image: "https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=800&q=80",
  },
  {
    id: 6,
    title: "버지니아 SB 164 부결: 헴프 THC 음료 별도 판매경로 무산",
    summary: "버지니아주 의회에서 헴프 THC 음료에 대한 별도 판매 경로를 신설하는 SB 164 법안이 부결됐다. 헴프 음료 업계의 규제 명확화 시도가 좌절됐다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-04",
    country: "미국",
    link: "https://www.cannabisbusinesstimes.com/us-states/virginia/news/15822985/virginia-lawmakers-reject-governors-substitute-for-cannabis-sales-bill",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800&q=80",
  },
  {
    id: 7,
    title: "FBI, 버지니아 Louise Lucas 상원의원 사무실 + 헴프 THC 매장 동시 압수수색",
    summary: "FBI가 버지니아주 Louise Lucas 상원의원 사무실과 헴프 THC 판매 매장을 동시에 압수수색했다. 헴프 THC 음료 규제 논쟁이 법적 분쟁으로 확대되는 양상이다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-06",
    country: "미국",
    link: "https://mjbizdaily.com/news/fbi-raids-virginia-lawmaker-connected-to-hemp-thc-shop/615882/",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&q=80",
  },
  {
    id: 8,
    title: "독일 MedCanG 개정안, Q2 시행 임박 — 외국 처방 인정 중단·가격 통제 도입",
    summary: "독일 의료대마법(MedCanG) 개정안이 2분기 시행을 앞두고 있다. 외국 처방전 인정 중단과 가격 통제 조항 도입으로 독일 의료대마 시장 구조가 크게 변화할 전망이다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-07",
    country: "독일",
    link: "https://businessofcannabis.com/deals-courts-and-coalition-splits-germanys-cannabis-market-braces-for-change/",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
  },
  {
    id: 9,
    title: "캐나다 PEI주, 대마 합법 연령 19→21세 상향 검토 — 청소년 보호 명분",
    summary: "캐나다 프린스에드워드아일랜드(PEI)주가 대마 합법 구매 연령을 현행 19세에서 21세로 상향하는 방안을 검토 중이다. 청소년 보호를 명분으로 내세우고 있으나 업계의 반발이 예상된다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-07",
    country: "캐나다",
    link: "https://stratcann.com/news/pei-cannabis-age-of-access-21/",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
  },
  {
    id: 10,
    title: "호주 의료 대마 매출 H2 2025년 -28.5% 급락 — Penington Institute 보고서",
    summary: "Penington Institute 보고서에 따르면 호주 의료 대마 매출이 2025년 하반기에 전년 동기 대비 28.5% 급락했다. 규제 강화와 공급 과잉이 복합적으로 작용한 것으로 분석된다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-04",
    country: "호주",
    link: "https://www.penington.org.au/medicinal-cannabis-sales-fall-nearly-30-as-enforcement-crackdown-takes-effect/",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80",
  },
  // 산업·비즈니스 → global
  {
    id: 11,
    title: "Canopy Growth, Spectrum Therapeutics 의료 대마 포트폴리오 확장 발표",
    summary: "Canopy Growth의 자회사 Spectrum Therapeutics가 의료 대마 제품 포트폴리오를 확장한다고 발표했다. 신규 처방 의약품 라인업 추가와 함께 유럽 시장 진출을 가속화할 계획이다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-09",
    country: "캐나다",
    link: "https://canopygrowth.com/investors/news-releases/canopy-growth-and-spectrum-therapeutics-expand-medical-portfolio-with-new-30-and-90-pack-softgels-and-enhanced-dosing-options/",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
  },
  {
    id: 12,
    title: "High Tide 독일 자회사 Remexian Pharma, 분기 7.6톤 의료 대마 판매 달성",
    summary: "High Tide의 독일 자회사 Remexian Pharma가 분기 7.6톤의 의료 대마 판매를 달성했다고 밝혔다. 독일 의료대마 합법화 이후 급성장하는 시장에서 캐나다 LP들의 수출이 본격화되고 있다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-09",
    country: "캐나다/독일",
    link: "https://hightideinc.com/high-tide-reports-record-quarterly-distribution-of-7-6-tonnes-of-medical-cannabis-through-remexian-pharma-gmbh-accelerating-german-market-leadership/",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80",
  },
  {
    id: 13,
    title: "Cannara Biotech, Medican Organic 인수 마무리 — Valleyfield 생산 시설 통합",
    summary: "Cannara Biotech가 Medican Organic 인수를 마무리하고 Valleyfield 생산 시설을 통합했다. 이번 인수로 Cannara의 연간 생산 능력이 대폭 확대될 전망이다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-09",
    country: "캐나다",
    link: "https://www.newcannabisventures.com/organigram-global-closes-european-acquisition/",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
  },
  {
    id: 14,
    title: "Organigram, Sanity Group 인수 마무리 — 250M 규모 EU 시장 통합 가속",
    summary: "Organigram이 독일 Sanity Group 인수를 마무리했다. 약 2억 5천만 달러 규모의 이번 거래로 Organigram은 유럽 의료대마 시장에서의 입지를 크게 강화하게 됐다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-05",
    country: "캐나다/독일",
    link: "https://www.newcannabisventures.com/organigram-global-closes-european-acquisition/",
    image: "https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=800&q=80",
  },
  {
    id: 15,
    title: "Jushi Holdings, 160M 비희석화 부채 리파이낸싱 완료 — 280E 폐지 효과 반영",
    summary: "미국 MSO Jushi Holdings가 1억 6천만 달러 규모의 비희석화 부채 리파이낸싱을 완료했다. DEA Schedule III 재분류로 인한 280E 세금 폐지 효과가 재무 구조 개선에 기여한 것으로 분석된다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-06",
    country: "미국",
    link: "https://www.cannabisbusinesstimes.com/finance/news/15820777/jushi-holdings-refinances-credit-facilities-with-160-million-nondilutive-debt-financing",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800&q=80",
  },
  {
    id: 16,
    title: "이스라엘 흡연 의료대마 폐지 권고 — 산업 충격 가시화",
    summary: "이스라엘 보건부의 흡연 의료대마 단계적 폐지 권고로 산업계에 충격이 가해지고 있다. 이스라엘은 전 세계 의료대마 수출 주요국 중 하나로, 이번 정책 변화가 글로벌 시장에도 영향을 미칠 전망이다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-04",
    country: "이스라엘",
    link: "https://mjbizdaily.com/news/should-medical-cannabis-be-smoked-israel-debates-removing-smokeable-flower/615816/",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&q=80",
  },
  {
    id: 17,
    title: "미국 Target, 헴프 THC 음료 판매 3개 주 추가 확장 — 11월 연방 금지 임박에도",
    summary: "미국 대형 유통업체 Target이 헴프 THC 음료 판매를 3개 주에 추가 확장했다. 11월 연방 차원의 금지 조치가 임박한 상황에서도 판매를 확대하는 것이어서 주목된다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-08",
    country: "미국",
    link: "https://www.marijuanamoment.net/target-is-launching-hemp-thc-drink-sales-in-three-of-the-u-s-s-most-populous-states/",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
  },
  {
    id: 18,
    title: "캐나다 일간 대마 사용자 인구 5.7% — Statistics Canada 2023/24 데이터",
    summary: "Statistics Canada의 2023/24년 데이터에 따르면 캐나다 성인 인구의 5.7%가 매일 대마를 사용하는 것으로 나타났다. 합법화 이후 일간 사용자 비율이 꾸준히 증가하는 추세다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-09",
    country: "캐나다",
    link: "https://stratcann.com/news/canadas-cannabis-industry-positioned-global-industry/",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
  },
  {
    id: 19,
    title: "미시간주, 1월 1일 시행 24% 도매 소비세 영향으로 1분기 매출 압박 가시화",
    summary: "미시간주에서 2026년 1월 1일부터 시행된 24% 도매 소비세의 영향으로 1분기 대마 매출 압박이 가시화되고 있다. 소매업체들의 마진 압축과 소비자 가격 상승이 동반되고 있다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-07",
    country: "미국",
    link: "https://www.cannabisbusinesstimes.com/us-states/michigan/news/15818403/8-michigan-senators-plan-to-repeal-states-24-cannabis-tax",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80",
  },
  {
    id: 20,
    title: "캐나다→호주·이스라엘 의료 대마 수출 패러다임 변화 — 글로벌 의료 채널 강화",
    summary: "캐나다 LP(라이선스 생산자)들이 호주와 이스라엘 등 주요 의료대마 수입국으로의 수출 전략을 강화하고 있다. 각국의 규제 변화에 맞춘 맞춤형 제품 공급이 핵심 경쟁력으로 부상하고 있다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-09",
    country: "캐나다",
    link: "https://stratcann.com/news/canadas-cannabis-industry-positioned-global-industry/",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
  },
  // R&D
  {
    id: 21,
    title: "Monash University 연구: 고용량 THC 의료 대마 부작용 50%+ 정신증상 포함",
    summary: "호주 Monash University 연구팀이 고용량 THC 의료 대마 사용자의 50% 이상에서 정신증상을 포함한 부작용이 나타났다는 연구 결과를 발표했다. 적정 용량 관리의 중요성이 다시 부각되고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-04",
    country: "호주",
    link: "https://cedclinic.com/high-potency-cannabis-linked-to-dramatically-higher-risk-of-psychotic-episodes/",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
  },

  {
    id: 23,
    title: "Bloomwell 독일 환자 2,500명 설문: 47.5% '약국 대마가 불법 시장보다 저렴' — 합법 시장 정착",
    summary: "Bloomwell이 독일 의료대마 환자 2,500명 이상을 대상으로 실시한 설문에서 47.5%가 약국 대마가 불법 시장보다 저렴하다고 응답했다. 합법화 전 57%가 불법 시장을 이용했으나 현재는 82%가 약국이 더 안전하다고 인식한다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-07",
    country: "독일",
    link: "https://luminorecruit.com/germanys-medical-cannabis-market-and-what-could-be-at-risk-in-2025/",
    image: "https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=800&q=80",
  },
  {
    id: 24,
    title: "연구: 사이키델릭 1회 + 심리치료, 알코올 사용장애에 '안전하고 효과적' — Schedule III 후 시너지",
    summary: "실로사이빈 1회 투여와 심리치료를 병행하는 치료법이 알코올 사용장애에 안전하고 효과적이라는 신규 연구 결과가 발표됐다. 32명 의원 연합의 FDA 검토 가속 촉구와 맞물려 사이키델릭·카나비스 정신건강 약물 모멘텀이 확산되고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-07",
    country: "미국",
    link: "https://www.marijuanamoment.net/psychedelics-have-demonstrated-potential-for-treating-drug-addiction-and-alcoholism-new-research-shows/",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
  },
  {
    id: 25,
    title: "캐나다 정부 보고서: 대마 매출 증가 + 알코올 매출 감소 동시 진행 — Substitution Effect 확인",
    summary: "캐나다 정부 보고서에서 대마 합법화 이후 대마 매출 증가와 알코올 매출 감소가 동시에 진행되는 대체 효과(Substitution Effect)가 확인됐다. 공중보건 관점에서 긍정적 신호로 해석된다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-08",
    country: "캐나다",
    link: "https://www.marijuanamoment.net/marijuana-sales-are-rising-and-alcohol-is-on-the-decline-as-consumer-preferences-evolve-government-data-in-canada-shows/",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
  },
  {
    id: 26,
    title: "히브리대 후속 연구: CBD·CBG의 인포스포크레아틴/리소좀 메커니즘, 지방간 외 신경보호 가능성",
    summary: "히브리대학교 연구팀이 CBD와 CBG가 인포스포크레아틴 및 리소좀 메커니즘을 통해 지방간 질환 개선 외에도 신경보호 효과를 나타낼 수 있다는 후속 연구 결과를 발표했다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-06",
    country: "이스라엘",
    link: "https://www.timesofisrael.com/israeli-researchers-find-cannabis-compounds-could-lead-to-1st-drug-for-fatty-liver-disease/",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800&q=80",
  },

  {
    id: 28,
    title: "체코 화학기술대학 후속 연구: CBDV + CBG/CBN 조합, 만성 장 염증에 시너지 효과",
    summary: "체코 화학기술대학 연구팀이 CBDV와 CBG/CBN 조합이 만성 장 염증 치료에 시너지 효과를 나타낸다는 후속 연구 결과를 발표했다. 마이너 카나비노이드의 복합 활용 가능성이 주목받고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-06",
    country: "체코",
    link: "https://www.cochrane.org/about-us/news/no-clear-evidence-cannabis-based-medicines-relieve-chronic-nerve-pain",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
  },
  {
    id: 29,
    title: "RAND·UCSF 연구진: Schedule III 후속 효과 — DEA Schedule I 유지 시 연구 제약 지속 경고",
    summary: "RAND와 UCSF 연구진이 DEA Schedule III 재분류 이후에도 일부 연구 제약이 지속될 수 있다고 경고했다. 완전한 연구 자유화를 위해서는 추가적인 규제 개혁이 필요하다는 입장이다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-05",
    country: "미국",
    link: "https://theconversation.com/reclassification-of-marijuana-opens-doors-for-much-needed-medical-research-into-the-benefits-and-risks-of-the-drug-281403",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&q=80",
  },
  {
    id: 30,
    title: "PolitiFact 분석: 카나비스 사용장애(CUD) 약 30% 비율 — 합법화 시장의 공중보건 과제",
    summary: "PolitiFact 분석에 따르면 대마 사용자의 약 30%에서 카나비스 사용장애(CUD)가 나타나는 것으로 집계됐다. 합법화 시장 확대와 함께 공중보건 관리 체계 강화가 과제로 부상하고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-04",
    country: "미국",
    link: "https://www.marijuanamoment.net/theres-strong-public-demand-for-bigger-marijuana-reform-than-trumps-rescheduling-move-federally-funded-study-shows/",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80",
  },
];

// ── 2026-05-04 주간 뉴스 ──────────────────────────────────────────────────

const ARTICLES_20260504: Article[] = [
  // 정책·규제
  {
    id: 31,
    title: "DEA Schedule III 재분류 연방관보 게재 — 4월 28일부 공식 발효",
    summary: "4월 27일 DOJ가 3건의 문서를 연방관보 공개검열페이지에 등록하고, 4월 28일 공식 게재로 Schedule III 재분류가 공식 발효됐다. 280E 즉시 폐지 및 의료 대마 사업자에게 60일 우선심사 신청 기회가 부여됐다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-04-28",
    country: "미국",
    link: "https://foleyhoag.com/news-and-insights/publications/alerts-and-updates/2026/april/cannabis-rescheduling-doj-treasury-and-dea-updates-since-the-april-23-order/",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
  },


  {
    id: 34,
    title: "하원 세출소위, DOJ의 대마 재분류 권한 차단하는 예산안 조항 통과",
    summary: "하원 세출소위원회가 DOJ의 대마 재분류 권한 행사를 차단하는 예산법안 조항을 통과시켰다. 의회 연구진은 재분류 명령이 주(州) 라이선스 사업자를 즉시 연방법 준수 상태로 만들지 않는다고 지적했다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-04-30",
    country: "미국",
    link: "https://www.cannabisbusinesstimes.com/cannabis-rescheduling/news/15750787/us-house-subcommittee-advances-bill-to-prevent-cannabis-rescheduling-under-doj",
    image: "https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=800&q=80",
  },
  {
    id: 35,
    title: "아이다호 적극적 대마 합법화 반대 운동 — 청소년 보호 명분 후 자체 폐기",
    summary: "아이다호주에서 대마 합법화에 반대하는 적극적 운동이 전개됐으나 청소년 보호를 명분으로 내세운 뒤 자체 폐기됐다. 미국 내 대마 정책 논쟁의 복잡한 양상을 보여준다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-04-30",
    country: "미국",
    link: "https://www.marijuanamoment.net/idaho-lawmakers-approve-resolution-asking-voters-to-reject-medical-cannabis-ballot-measure/",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800&q=80",
  },
  {
    id: 36,
    title: "Florida·NJ·VA, 두 번째 성인용 대마 폐지 시도 무산 — 매사추세츠만 유일 남아",
    summary: "플로리다, 뉴저지, 버지니아에서 성인용 대마 합법화를 폐지하려는 두 번째 시도가 모두 무산됐다. 현재 미국에서 성인용 대마 폐지를 추진 중인 주는 매사추세츠만 남게 됐다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-04-28",
    country: "미국",
    link: "https://mjbizdaily.com/news/second-state-level-effort-to-recriminalize-adult-use-marijuana-sales-fails/615867/",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&q=80",
  },
  {
    id: 37,
    title: "UK 의료대마 이해관계자 연합, 해외여행 시 처방대마 휴대 가이드 발표",
    summary: "영국 의료대마 이해관계자 연합이 해외여행 시 처방 의료대마를 합법적으로 휴대하는 방법에 대한 공식 가이드를 발표했다. 환자들의 해외여행 시 법적 불확실성을 해소하기 위한 조치다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-04-29",
    country: "영국",
    link: "https://cannabishealthnews.co.uk/2026/04/29/industry-publishes-new-guidance-for-patients-travelling-with-medical-cannabis/",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
  },
  {
    id: 38,
    title: "캘리포니아, Prop 64 합법화 10주년 — 누적 세수 약 70억 달러 달성",
    summary: "캘리포니아주가 Prop 64 대마 합법화 10주년을 맞았다. 합법화 이후 누적 세수가 약 70억 달러에 달하는 것으로 집계됐으며, 불법 시장 축소와 사회적 형평성 프로그램 재원 마련에 기여했다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-04-29",
    country: "미국",
    link: "https://finance.yahoo.com/economy/policy/articles/california-marks-10-years-cannabis-185947664.html",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80",
  },
  {
    id: 39,
    title: "아리조나 SB 1725: 자기 집 마당에서 대마 흡연 시 최대 4개월 징역 — 5/3 전체회의 통과",
    summary: "아리조나주 SB 1725 법안이 5월 3일 전체회의를 통과했다. 이 법안은 자신의 집 마당에서 대마를 흡연할 경우 최대 4개월 징역에 처할 수 있도록 규정하고 있어 논란이 되고 있다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-04-30",
    country: "미국",
    link: "https://www.marijuanamoment.net/arizona-lawmakers-advance-bill-to-punish-people-over-excessive-marijuana-odor-or-smoke/",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
  },
  {
    id: 40,
    title: "프랑스·스페인 신규 의료 대마 시장 — 플라워 없는 추출물·캡슐 중심 출범",
    summary: "프랑스와 스페인이 신규 의료 대마 시장을 출범시켰다. 두 나라 모두 플라워 제품 없이 추출물과 캡슐 형태의 의약품 중심으로 시장을 구성했다는 점이 특징이다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-01",
    country: "프랑스/스페인",
    link: "https://businessofcannabis.com/is-europe-moving-away-from-cannabis-flower/",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
  },
  // 산업·비즈니스 → global

  {
    id: 42,
    title: "Tilray·Aurora·Canopy Growth: 재분류 호재에도 52주 고점 대비 67%, 46%, 48% 하락 — 구조적 약점 노출",
    summary: "Schedule III 호재로 일시 급등했으나 Tilray($188M Q3 매출), Aurora, Canopy Growth 모두 흑자 미달성 상태다. 캘리포니아 매출 -11%, 가격 압축, 만성 적자 등 구조적 약점이 부각되고 있다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-04-28",
    country: "캐나다",
    link: "https://247wallst.com/investing/2026/04/23/finally-marijuana-gets-reclassified-but-are-pot-stocks-still-too-risky/",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80",
  },

  {
    id: 44,
    title: "Cornbread Hemp, Medicare CBD 파일럿 프로그램 독점 공급권 확보 — 6.8만 헬스케어 거점",
    summary: "Cornbread Hemp가 GPO Alliant Purchasing(6.8만 헬스케어 거점)과 USDA 유기농 CBD 독점 공급 계약을 체결했다. 4월 출범 Medicare CBD 파일럿 프로그램의 첫 공급사로 선정됐으나 11월 헴프 재정의로 위협받고 있다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-04-30",
    country: "미국",
    link: "https://sorsetech.com/hemp-and-cannabis-regulatory-roundup-april-2026/",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800&q=80",
  },

  {
    id: 46,
    title: "Cantourage Group, 베를린 발 의료 대마 'Fast Track' 유럽 공급망 구축 발표",
    summary: "독일 Cantourage Group이 베를린을 거점으로 한 의료 대마 'Fast Track' 유럽 공급망 구축 계획을 발표했다. 독일 합법화 이후 유럽 의료대마 허브로서의 위상을 강화하려는 전략이다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-04-30",
    country: "독일",
    link: "https://www.eqs-news.com/news/corporate/cantourage-group-se-cantourage-significantly-increases-profitability-in-the-first-quarter-of-2026/4a85886d-3630-4e6e-9dc7-7c8dfaaa192c",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
  },
  {
    id: 47,
    title: "UK·독일 의료 대마 시장 2025년 두 배 성장 — Prohibition Partners 보고서",
    summary: "Prohibition Partners 보고서에 따르면 영국과 독일의 의료 대마 시장이 2025년에 전년 대비 두 배 성장한 것으로 나타났다. 두 나라 모두 규제 완화와 처방 접근성 확대가 성장을 견인했다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-04-27",
    country: "영국/독일",
    link: "https://businessofcannabis.com/new-report-uk-and-germany-medical-cannabis-markets-both-double-in-2025/",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80",
  },
  {
    id: 48,
    title: "Charlotte's Web, BAT와 거래: 채권 전환 + 10M 지분 투자로 재무 강화",
    summary: "Charlotte's Web이 영국 담배 대기업 BAT(British American Tobacco)와 채권 전환 및 1천만 달러 지분 투자 거래를 체결했다. 빅 담배 기업의 CBD 시장 진출이 본격화되는 신호로 해석된다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-04-29",
    country: "미국",
    link: "https://investors.charlottesweb.com/press-releases/press-release-details/2026/Charlottes-Web-Announces-Transaction-with-BAT-Debenture-Conversion-and-US10M-Equity-Investment-to-Strengthen-Balance-Sheet/default.aspx",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
  },
  {
    id: 49,
    title: "이스라엘 2025년 의료 대마 매출 3.72억 달러 — 캐나다발 수입 30.1톤 사상 최대",
    summary: "이스라엘의 2025년 의료 대마 매출이 3억 7,200만 달러를 기록했다. 캐나다에서 수입한 의료대마가 30.1톤으로 사상 최대치를 달성했으며, 이스라엘이 주요 의료대마 수입국으로 자리매김했다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-04-29",
    country: "이스라엘",
    link: "https://mjbizdaily.com/news/israel-threatens-tariffs-on-canadian-medical-marijuana-imports/403340/",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
  },
  {
    id: 50,
    title: "브라질 2026년 의료 대마 시장 +45% 성장 — 신규 규정으로 확장 본격화",
    summary: "브라질 의료 대마 시장이 2026년에 전년 대비 45% 성장할 것으로 전망된다. 신규 규정 도입으로 처방 접근성이 확대되고 국내 생산이 허용되면서 시장 확장이 본격화되고 있다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-01",
    country: "브라질",
    link: "https://internationalcbc.com/brazilian-medical-cannabis-decree-takes-effect/",
    image: "https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=800&q=80",
  },
  // R&D
  {
    id: 51,
    title: "CED Clinic, 4월 29일 신규 임상 연구 다이제스트 발표 — 동료심사 연구 10편 큐레이션",
    summary: "CED Clinic이 임상 적용 가능한 4월 최신 동료심사 연구 10편을 큐레이션한 연구 다이제스트를 발표했다. 통증·수면·정신건강 등 다양한 영역을 다루며 4월 22일 게재본의 후속이다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-04-29",
    country: "미국",
    link: "https://cedclinic.com/research-digest-10-recent-studies-april-22-2026/",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
  },

  {
    id: 53,
    title: "연구: 청소년 대마 합법화 우려와 달리 실제 청소년 사용량 감소 또는 안정",
    summary: "대마 합법화 이후에도 청소년 소비량은 우려와 달리 폭증하지 않았음을 보여주는 신규 연구가 재확산되고 있다. SAMHSA·CDC 데이터 통합 분석 결과로, 합법화 정책 논의에서 주요 논거로 활용되고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-04-28",
    country: "미국",
    link: "https://www.marijuanamoment.net/teen-marijuana-use-continues-to-drop-as-more-states-legalize-federally-funded-study-shows-contradicting-opponents-claims/",
    image: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=800&q=80",
  },
  {
    id: 54,
    title: "연구: 의료 대마 사용자, 오피오이드·수면제·항우울제 등 다른 약물 사용 감소",
    summary: "의료 대마 사용이 오피오이드·수면제·항우울제 사용량 감소와 상관관계가 있음을 확인하는 신규 연구가 발표됐다. 만성통증 환자에서 가장 두드러진 약물 대체 효과가 나타났으며, Schedule III 이후 임상 연구 가속화가 기대된다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-04-27",
    country: "미국",
    link: "https://www.marijuanamoment.net/medical-marijuana-helps-people-stop-using-opioids-sleeping-aids-and-other-prescription-drugs-study-shows/",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80",
  },


  {
    id: 57,
    title: "UCLA JAMA 연구 재조명: 의료 대마, 불안·우울·PTSD에 효과 미흡 — 2,500편 메타분석",
    summary: "UCLA 연구팀이 JAMA에 발표한 2,500편 메타분석 연구가 재조명되고 있다. 의료 대마가 불안·우울·PTSD 치료에 기대만큼 효과적이지 않다는 결론으로, 과도한 기대에 대한 경고로 해석된다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-04-30",
    country: "미국",
    link: "https://www.scientificamerican.com/article/medical-cannabis-isnt-an-effective-treatment-for-anxiety-depression-or-ptsd/",
    image: "https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=800&q=80",
  },
  {
    id: 58,
    title: "Cochrane Review 2026 후속 분석: CBD 단독, 신경병증 통증 효과 미달 — 복합 처방 필요",
    summary: "Cochrane Review 2026 후속 분석에서 CBD 단독 투여는 신경병증 통증 치료에 효과가 미달한다는 결론이 나왔다. THC와의 복합 처방이 더 효과적이라는 근거가 축적되고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-04-28",
    country: "국제",
    link: "https://www.cochrane.org/about-us/news/no-clear-evidence-cannabis-based-medicines-relieve-chronic-nerve-pain",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&q=80",
  },
  {
    id: 59,
    title: "UCSD CMCR 만성 요통 임상 결과 후속: Cannabis sativa DKJ127 전임상 유효성 확인",
    summary: "UCSD 대마 의학 연구센터(CMCR)의 만성 요통 임상 결과 후속으로 Cannabis sativa DKJ127 균주의 전임상 유효성이 확인됐다. 특정 균주의 표준화된 의약품 개발 가능성이 높아지고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-01",
    country: "미국",
    link: "https://cmcr.ucsd.edu/index.php/news-2/homeblog/484-featured-publication-is-cannabis-a-solution-for-chronic-low-back-pain",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
  },
  {
    id: 60,
    title: "프랑스 INSERM, Schedule III 후 미국과 EU 의료 대마 임상 데이터 공동 연구 제안",
    summary: "프랑스 국립보건의학연구원(INSERM)이 미국의 Schedule III 재분류 이후 미국과 EU의 의료 대마 임상 데이터를 공동 연구하는 방안을 제안했다. 대서양 양안의 연구 협력이 본격화될 전망이다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-02",
    country: "프랑스",
    link: "https://theconversation.com/reclassification-of-marijuana-opens-doors-for-much-needed-medical-research-into-the-benefits-and-risks-of-the-drug-281403",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&q=80",
  },
];

// ── 국내 기사 ──────────────────────────────────────────────────────────────

const ARTICLES_DOMESTIC: Article[] = [
  {
    id: 61,
    title: "첨단 바이오소재 헴프 산업 중심지 부상 경북 북부권",
    summary: "경북 북부권이 산업용 헴프(HEMP) 중심지로 자리매김하고 있다. 과거 삼베 생산에 머물렀던 대마 산업을 첨단 바이오소재 산업으로 전환해 국산 품종 개발부터 완제의약품 제조까지 전주기 가치사슬을 구축했다. 6월 신규 규제자유특구 지정 최종 절차를 앞두고 있다.",
    category: "domestic",
    categoryLabel: "국내",
    date: "2026-05-13",
    country: "한국",
    link: "https://www.fnnews.com/news/202605130930110673",
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80",
    featured: true,
  },
  {
    id: 62,
    title: "정부, 의료용 대마 CBD 국산화 첫발 — 농식품부 57억 규모 사업 착수",
    summary: "정부가 그간 해외 수입에 의존해온 의료용 대마 성분 칸나비디올(CBD) 원료의약품 국산화에 본격 착수했다. 네오켄바이오 주관 컨소시엄이 총 57억원 규모로 재배·추출·허가 전 과정을 수행하며, HLB생명과학R&D가 비임상·CMC·IND 준비를 맡는다.",
    category: "domestic",
    categoryLabel: "국내",
    date: "2026-04-25",
    country: "한국",
    link: "https://www.inews24.com/view/1963211",
    image: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&q=80",
  },
  {
    id: 63,
    title: "강원대 최익영·엄태영 교수팀, 의료용 대마 CBD 생합성 조절 메커니즘 규명",
    summary: "강원대학교 공동연구팀이 의료용 대마의 주요 기능성 물질인 칸나비디올(CBD) 생합성 조절 메커니즘을 규명했다. 개화 단계와 품종에 따라 약 2,400개 이상의 유전자 발현 차이가 확인됐으며, 연구 성과는 농업학 분야 상위 5% 국제학술지 'Industrial Crops & Products'에 게재됐다.",
    category: "domestic",
    categoryLabel: "국내",
    date: "2026-03-15",
    country: "한국",
    link: "https://www.lecturernews.com/news/articleView.html?idxno=198687",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
  },
  {
    id: 79,
    title: "경북도, 의료용 헴프 산업기지 본격 추진 — CBD 원료의약품 GMP 시설 2027년 가동 목표",
    summary: "경북도가 북부권을 산업용 헴프(HEMP) 산업 거점으로 육성. 6월 신규 규제자유특구 최종 지정 여부 결정 전망. 네오켄바이오가 150억원 규모 CBD 원료의약품 GMP 제조시설 조성 중(2027년 가동 목표). 농림축산식품부 57억원 규모 공모사업 선정.",
    category: "domestic",
    categoryLabel: "국내",
    date: "2026-05-13",
    country: "한국",
    link: "https://www.kyongbuk.co.kr/news/articleView.html?idxno=4072683",
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80",
    source: "경북일보 5/13",
    featured: false,
  },
  {
    id: 80,
    title: "식약처, 해외직구 마약류 의심 식품 정기 기획검사 착수 — CBD·THC 등 55종 검사",
    summary: "식품의약품안전처가 대마 합법 국가의 온라인 쇼핑몰에서 판매되는 직구 젤리·음료 등 마약류 의심 제품에 대해 5~6월 기획검사 실시. 검사 항목은 CBD, THC 등 대마 성분과 암페타민·미트라지닌 등 55종.",
    category: "domestic",
    categoryLabel: "국내",
    date: "2026-05-11",
    country: "한국",
    link: "https://www.asiatoday.co.kr/kn/view.php?key=20260511010002340",
    image: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&q=80",
    source: "아시아투데이 5/11",
    featured: false,
  },
  {
    id: 105,
    title: "'대마 아닌 홉에서 추출한 CBD'…반려동물 헬스케어 새 시장 열리나",
    summary: "대마가 아닌 홉(Hops)에서 추출한 CBD가 반려동물 헬스케어 분야의 새로운 소재로 주목받고 있다. 17일 국회의원회관에서 열린 '홉 유래 바이오산업 육성 포럼'에서 홉 유래 CBD의 과학적 특성과 산업적 활용 가능성이 소개됐다. 비대마 CBD 시장은 2030년 80조원 규모로 성장할 것으로 전망된다.",
    category: "domestic",
    categoryLabel: "국내",
    date: "2026-06-17",
    country: "한국",
    link: "https://n.news.naver.com/article/421/0009009387?sid=101",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80",
    source: "뉴스1 6/17",
    featured: false,
  },
  {
    id: 121,
    title: "HLB생명과학R&D, 경북 산업용 헴프 규제자유특구 참여 — 미량 칸나비노이드 신약 개발 착수",
    summary: "HLB생명과학R&D가 중소벤처기업부·국무조정실 지정 '경북 산업용 헴프(대마) 규제자유특구' 공동 참여기관으로 선정돼 미량 칸나비노이드 기반 차세대 신약개발에 착수했다. 네오켄바이오·에이팩·엔비더팜·토포랩·아이엔지알 등이 공동 수행하며, KIST·경북바이오산업연구원 등과 함께 4년간 총 296억원을 투입한다. 기존 CBD 중심에서 CBG·CBC·CBN 등 미량 칸나비노이드로 실증 범위를 확대하는 것이 핵심으로, 국내 헴프 산업의 고도화를 보여주는 대표 사례다.",
    category: "domestic",
    categoryLabel: "국내",
    date: "2026-07-06",
    country: "한국",
    link: "https://www.hankyung.com/article/202607066881i",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
    source: "한국경제 7/6",
    featured: false,
  },
  {
    id: 122,
    title: "서미화·김형동 의원·식약처, '대마 성분 의약품 도입 방안 정책 토론회' 개최 — CBD 국내 생산 필요성 공론화",
    summary: "서미화·김형동 의원과 식품의약품안전처가 7일 국회의원회관에서 '대마 성분 의약품 도입 방안 정책 토론회'를 공동 개최했다. 약물난치성 뇌전증 환자의 치료기회 확대를 위해 의료용 CBD(에피디올렉스) 국내 생산·공급체계 구축이 필요하다는 데 전문가들이 의견을 모았다. 현재 전량 해외 수입에 의존하는 구조의 한계와 복잡한 행정절차가 지적됐으며, 한의계는 대마 성분 한약제제 개발 기반 마련을 촉구했다. 식약처는 엄격한 안전관리를 전제로 입법 과정에 참여하겠다는 입장을 밝혔다.",
    category: "domestic",
    categoryLabel: "국내",
    date: "2026-07-07",
    country: "한국",
    link: "https://www.akomnews.com/bbs/board.php?bo_table=news&wr_id=67689",
    image: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&q=80",
    source: "한의신문 7/7",
    featured: false,
  },
  {
    id: 123,
    title: "신성범 의원, 'THC 0.3% 이하 헴프 대마 제외' 마약류관리법 개정안 대표발의 — 전 산업 활용 기반 마련",
    summary: "국민의힙 신성범 의원이 7일 THC 함유량이 건조 중량 기준 0.3% 이하인 헴프(Hemp)를 대마의 범위에서 완전 제외하는 '마약류 관리에 관한 법률 일부개정안'을 대표발의했다. 의료용은 물론 기능성 식품·화장품·섬유·사료 등 다양한 산업 분야에서 헴프를 합법적으로 활용할 수 있는 제도적 기반을 마련하는 것이 핵심이다. 경북 헴프 규제자유특구에서 확인된 산업화 가능성을 전국적으로 확대하는 입법으로, 서미화·윤준병·김형동 의원에 이어 네 번째 대마 관련 법안 발의로 국회 입법 동력이 가속화되고 있다.",
    category: "domestic",
    categoryLabel: "국내",
    date: "2026-07-08",
    country: "한국",
    link: "https://www.akomnews.com/bbs/board.php?bo_table=news&wr_id=67692",
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80",
    source: "한의신문 7/8",
    featured: false,
  },
];


// ── 2026-05-25 주간 뉴스 ──────────────────────────────────────────────────

const ARTICLES_20260525: Article[] = [
  {
    id: 84,
    title: "버지니아 Spanberger 주지사, 성인용 대마 판매 합법화 법안 거부권 행사",
    summary: "버지니아 Spanberger 주지사가 성인용 대마 소매 판매 합법화 법안에 거부권을 행사했다. 주지사는 현행 의료 대마 시스템 정비가 우선이라는 입장을 밝혔으며, 산업계는 즉각 반발했다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-21",
    country: "미국",
    link: "https://www.marijuanamoment.net/virginia-governor-vetoes-marijuana-sales-legalization-bill/",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    source: "MM 뉴스레터 5/21",
    featured: false,
  },
  {
    id: 85,
    title: "美 교통부(DOT): 트럭 운전사·조종사, DEA 재분류에도 의료 대마 사용 시 처벌",
    summary: "미국 교통부(DOT)가 DEA의 대마 Schedule III 재분류 이후에도 트럭 운전사, 항공기 조종사 등 안전 민감 직종 종사자에 대한 대마 무관용 정책을 유지한다고 명확히 밝혔다. 연방 교통 안전 규정은 재분류와 무관하게 적용된다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-21",
    country: "미국",
    link: "https://www.marijuanamoment.net/dot-says-truck-drivers-and-pilots-will-still-be-punished-for-using-medical-marijuana-even-after-dea-rescheduling/",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    source: "MM 뉴스레터 5/21",
    featured: false,
  },
  {
    id: 86,
    title: "앨라배마 첫 의료 대마 판매점 개점 '며칠 앞으로' — 합법화 5년 만",
    summary: "앨라배마주 최초의 의료 대마 판매점이 며칠 내 개점을 앞두고 있다. 2021년 합법화 이후 5년간의 규제 정비 끝에 드디어 환자들이 공식 채널을 통해 의료 대마를 구입할 수 있게 됐다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-21",
    country: "미국",
    link: "https://www.marijuanamoment.net/alabama-is-days-away-from-its-first-medical-marijuana-dispensary-opening-five-years-after-legalization/",
    image: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&q=80",
    source: "MM 뉴스레터 5/21",
    featured: false,
  },
  {
    id: 87,
    title: "FDA, VERTANICAL 전스펙트럼 대마 추출물에 혁신치료제 지정 — 만성 요통 비오피오이드 치료제",
    summary: "FDA가 독일 VERTANICAL의 전스펙트럼 대마 추출물 VER-01에 혁신치료제(Breakthrough Therapy) 지정을 부여했다. 만성 요통 대상 동종 최초(first-in-class) 비오피오이드 치료제로, 대마 기반 의약품의 임상 개발에 중요한 이정표가 될 전망이다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-19",
    country: "독일/미국",
    link: "https://www.prnewswire.com/news-releases/fda-grants-breakthrough-therapy-designation-to-vertanicals-ver-01-a-first-in-class-non-opioid-investigational-treatment-for-chronic-low-back-pain-302774617.html",
    image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&q=80",
    source: "MM 뉴스레터 5/19",
    featured: false,
  },
  {
    id: 88,
    title: "Whitney Economics·GCNC 글로벌 대마 보고서: 가격 압축이 신흥시장 재편",
    summary: "Whitney Economics와 GCNC가 발표한 글로벌 대마 산업 보고서에 따르면, 전 세계적인 대마 가격 하락이 신흥 시장의 경쟁 구도를 빠르게 재편하고 있다. 저비용 생산국의 부상과 기존 강자들의 마진 압박이 동시에 진행 중이다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-21",
    country: "글로벌",
    link: "https://whitneyeconomics.com/",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    source: "MM 뉴스레터 5/21",
    featured: false,
  },
  {
    id: 89,
    title: "CBG, 류마티스 관절염 치료 가능성 — '항염 능력' 입증 (신규 연구)",
    summary: "신규 연구에서 대마 성분 CBG(칸나비게롤)가 류마티스 관절염에서 '항염 능력과 호중구 매개 면역 조절 치료 잠재력'을 보유한 것으로 확인됐다. CBG가 염증 면역세포의 관절 유입을 제한하는 조절 효과를 발휘하며, CBD 이후 차세대 치료 성분으로 주목받고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-21",
    country: "미국",
    link: "https://www.marijuanamoment.net/the-cannabis-component-cbg-shows-promise-in-treating-rheumatoid-arthritis-with-its-anti-inflammatory-capacity-study-finds/",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80",
    source: "MM 뉴스레터 5/21",
    featured: false,
  },
  {
    id: 90,
    title: "대마 합법화, 오피오이드 과다복용 '유의미한 감소'와 연관 — 1.075억명 분석 (연방 자금)",
    summary: "연방 자금 지원 신규 연구가 상업보험 가입 성인 1.075억명의 청구 데이터를 분석한 결과, 대마 합법화가 '비치명적 오피오이드 중독의 유의미한 감소'와 연관된 것으로 나타났다. 역대 최대 규모의 분석으로 대마의 오피오이드 대체 가능성을 강력히 시사한다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-20",
    country: "미국",
    link: "https://www.marijuanamoment.net/marijuana-legalization-is-linked-to-significant-reductions-in-opioid-overdoses-federally-funded-study-finds/",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80",
    source: "MM 뉴스레터 5/19·5/20",
    featured: false,
  },
  {
    id: 92,
    title: "대마, 비만 퇴치에 역할 가능 — '게으른 스토너' 통념 반박 (연방 자금)",
    summary: "연방 자금 지원 신규 연구: 만성 카나비노이드 노출, 특히 대마 추출물이 식이유발 비만 마우스 모델에서 체중 감소, 혈당 항상성 개선, 지방조직 기능 정상화를 유도했다. THC 단독 투여군과 전스펙트럼 추출물 투여군 모두 체중·내장지방 감소를 확인하며, 식사량이나 운동량은 변화가 없었다. 대마의 '식욕 자극' 통념과 정반대되는 장기 대사 변화 메커니즘이 주목된다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-19",
    country: "미국",
    link: "https://www.marijuanamoment.net/marijuana-can-play-a-role-in-combating-obesity-contrary-to-stereotypes-about-lazy-stoners-with-the-munchies-new-federally-funded-study-suggests/",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80",
    source: "MM 뉴스레터 5/19·5/20",
    featured: false,
  },
  {
    id: 91,
    title: "대마 추출물, 식단·운동 없이 비만 쥐 체중·혈당 정상화 — UC 리버사이드 연구",
    summary: "미국 캘리포니아대 리버사이드 연구팀이 비만 쥐에 대마 추출물을 30일간 투여한 결과, 식이 조절이나 운동 없이 체중 감소와 내장 지방·혈당 수치 정상화가 동시에 확인됐다. 전스펙트럼 추출물이 THC 단독보다 혈당 개선 효과가 더 뛰어났으며, 비만 치료의 새로운 대사 경로로 주목된다.",
    category: "domestic",
    categoryLabel: "국내",
    date: "2026-05-26",
    country: "한국",
    link: "https://n.news.naver.com/article/662/0000095966?sid=103",
    image: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&q=80",
    source: "농민신문 5/26",
    featured: false,
  },
];

// ── 2026-05-18 주간 뉴스 ──────────────────────────────────────────────────

const ARTICLES_20260518: Article[] = [
  {
    id: 64,
    title: "하원, 군 보훈처(VA) 의사의 의료 대마 권장 허용 수정안 통과",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-15",
    summary: "하원이 군 보훈처(VA) 의사들이 환자에게 의료 대마를 권장할 수 있도록 허용하는 수정안을 통과시켰음. 사이키델릭 치료 인식 제고 수정안도 함께 통과.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/house-votes-to-let-military-veterans-get-medical-marijuana-recommendations-from-va-doctors/",
    source: "Marijuana Moment 뉴스레터 5/15",
    featured: false,
  },
  {
    id: 65,
    title: "하원 세출위, Trump 행정부의 대마 재분류 차단 조항 가결 — 단 주(州) 의료대마 보호조항은 유지",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-15",
    summary: "하원 세출위원회가 법무부의 대마 재분류 조치를 차단하는 조항이 포함된 예산법안을 가결. 다만 연방 간섭으로부터 주 의료대마 법을 보호하는 기존 라이더는 유지.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/congressional-committee-votes-to-block-marijuana-rescheduling-even-as-trump-administration-moves-forward-with-the-reform/",
    source: "Marijuana Moment 뉴스레터 5/15",
    featured: false,
  },
  {
    id: 66,
    title: "루이지애나, 말기 환자 병원 내 의료 대마 사용 허용 법안 본회의 통과 임박",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-15",
    summary: "루이지애나 하원 보건·복지위원회가 말기·불가역적 질환 환자가 병원 내에서 의료 대마를 사용할 수 있도록 허용하는 상원 통과 법안을 승인.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/louisiana-bill-to-let-terminally-ill-patients-use-medical-marijuana-in-hospitals-advances-toward-final-passage/",
    source: "Marijuana Moment 뉴스레터 5/15",
    featured: false,
  },
  {
    id: 67,
    title: "Ilhan Omar 의원: 의회에서도 많은 사람이 대마를 피운다 발언",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-15",
    summary: "Rep. Ilhan Omar(D-MN) 의회에 대마를 피우는 사람들이 많다고 발언. 합법화 옹호자라고 해서 사용자라는 뜻은 아니다라며 처벌 대신 합법화 필요성 강조.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/there-are-a-lot-of-people-who-smoke-cannabis-in-congress-lawmaker-says/",
    source: "Marijuana Moment 뉴스레터 5/15",
    featured: false,
  },
  {
    id: 68,
    title: "콜롬비아 하원 1위원회, 대마 합법화 법안 가결",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-14",
    summary: "콜롬비아 하원 1위원회가 성인 대마 합법화 법안을 가결. 법안은 전체 하원 표결로 넘어가며, 상원 통과 시 라틴아메리카 최초 합법화 국가가 될 수 있음.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80",
    link: "https://www.marijuanamoment.net/colombian-lawmakers-approve-bill-to-legalize-marijuana/",
    source: "Marijuana Moment 뉴스레터 5/14",
    featured: false,
  },
  {
    id: 69,
    title: "루이지애나 의원, 대마 합법화 연구 태스크포스 신설 법안 발의",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-14",
    summary: "루이지애나 의원이 대마 합법화 가능성을 연구할 주 정부 태스크포스 신설 법안을 발의. 경제적 영향, 공중 보건, 법 집행 등을 검토 예정.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/louisiana-government-task-force-would-study-marijuana-legalization-under-lawmakers-new-proposal/",
    source: "Marijuana Moment 뉴스레터 5/14",
    featured: false,
  },
  {
    id: 70,
    title: "영국 고용항소심판소: 의료대마 양성 반응 철도노동자 해고는 차별 가능성",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-13",
    summary: "영국 고용항소심판소(EAT)가 의료 대마 복용으로 약물 검사 양성 반응이 나온 철도 노동자 해고가 장애 차별에 해당할 수 있다고 판단.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80",
    link: "https://www.peoplemanagement.co.uk/article/1957725/rail-worker-may-discriminated-against-positive-medical-cannabis-test-eat-finds",
    source: "Marijuana Moment 뉴스레터 5/13",
    featured: false,
  },
  {
    id: 71,
    title: "하원 세출위 보고서: DEA·FDA에 향정 헴프 단속 강화 지시",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-13",
    summary: "하원 세출위원회 보고서가 DEA와 FDA에 소비자 안전을 위협하는 비규제 대마 제품에 대한 단속을 강화하도록 지시.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/congressional-committee-directs-dea-to-crack-down-on-unregulated-cannabis-products-that-threaten-consumer-safety/",
    source: "Marijuana Moment 뉴스레터 5/13",
    featured: false,
  },
  {
    id: 72,
    title: "조지아 Kemp 주지사, 의료대마 확대 법안 서명 — 베이핑·신규 적응증 허용",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-13",
    summary: "조지아 Brian Kemp(R) 주지사가 신규 적응증 추가, 베이핑 허용, THC 농도 변경 등 의료대마 접근성 확대 법안에 서명.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/georgia-governor-signs-bill-to-expand-medical-marijuana-access-by-allowing-vaping-and-adding-new-qualifying-conditions/",
    source: "Marijuana Moment 뉴스레터 5/13",
    featured: false,
  },
  {
    id: 73,
    title: "아이오와 의회, 의료대마 약국 수 2배 확대 법안 주지사 송부",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-13",
    summary: "아이오와 의회가 의료 대마 약국 수를 2배로 늘리는 법안을 Kim Reynolds(R) 주지사에게 송부. 동시에 다른 주 거주자도 아이오와 의료인 인증이 있으면 등록 가능.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/iowa-bill-to-double-the-number-of-medical-marijuana-dispensaries-heads-to-governors-desk/",
    source: "Marijuana Moment 뉴스레터 5/13",
    featured: false,
  },
  {
    id: 74,
    title: "캘리포니아 하원, 대마 약국 드라이브스루 합법화 법안 통과",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-13",
    summary: "캘리포니아 하원이 대마 디스펜서리에 드라이브스루 창구 운영을 허용하는 법안을 통과. 지역 승인이 전제 조건.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/california-assembly-passes-bill-to-legalize-marijuana-dispensary-drive-thru-windows/",
    source: "Marijuana Moment 뉴스레터 5/13",
    featured: false,
  },
  {
    id: 75,
    title: "DEA, 의료대마 제조·유통·시험 사업체용 신규 등록서식 발표",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-12",
    summary: "DEA가 주 라이선스 의료 대마 제조·유통·시험 사업체용 등록 서식을 곧 출시 예정. Schedule III 재분류 보호를 활용하려는 사업체 대상. 디스펜서리용 기존 서식에 추가.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/dea-announces-new-marijuana-registration-forms-for-manufacturing-distribution-and-testing-businesses/",
    source: "Marijuana Moment 뉴스레터 5/12",
    featured: false,
  },
  {
    id: 76,
    title: "ATF, Schedule III 재분류 반영해 총기 구매 양식 의료대마 질문 수정",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-12",
    summary: "주류·담배·총기·폭발물국(ATF)이 의료 대마의 연방 합법 지위를 인정하는 총기 구매 양식 개정안 초안 공개. Trump의 Schedule III 재분류 후속 조치.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/new-atf-gun-form-recognizes-medical-marijuanas-federally-legal-status-under-trumps-rescheduling-move/",
    source: "Marijuana Moment 뉴스레터 5/12",
    featured: false,
  },
  {
    id: 77,
    title: "매사추세츠 의회, 대마 합법화 폐지안 부결 — 청원 운동으로 11월 투표 가능성",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-12",
    summary: "매사추세츠 의회 특별 합동 발의안위원회가 주 대마 합법화법을 폐지하는 안에 대해 조치를 취하지 않기로 권고. 폐지 운동가들은 11월 투표를 위해 추가 서명 수집 진행.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/massachusetts-lawmakers-decline-to-act-on-measure-to-roll-back-marijuana-legalization/",
    source: "Marijuana Moment 뉴스레터 5/12",
    featured: false,
  },
  {
    id: 78,
    title: "인디애나 공화당 상원의원, 2027년 회기 의료대마 합법화 법안 발의 예고",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-05-12",
    summary: "인디애나 공화당 상원의원이 2027년 회기에 의료대마 합법화 법안을 발의하겠다고 발표. Mike Braun(R) 주지사의 최근 발언 및 연방 차원 개혁 흐름에 동참.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    link: "https://www.marijuanamoment.net/indiana-gop-senator-announces-new-bill-to-legalize-medical-marijuana-in-the-state/",
    source: "Marijuana Moment 뉴스레터 5/12",
    featured: false,
  },
  {
    id: 81,
    title: "미국 3대 대마 기업(MSO) 대상 RICO 집단소송 제기 — '빅 토바코'식 유해성 은폐 의혹",
    summary: "Cresco Labs, Green Thumb Industries, Verano Holdings 등 미국 대형 대마 운영사들이 RICO(조직범죄방지법) 위반 혐의로 제소됐다. 12개 주 40여 명의 원고는 이들이 제품의 건강 유해성을 숨기고 유리한 연구만 후원하는 등 과거 담배 회사의 전략을 답습했다고 주장했다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-18",
    country: "미국",
    link: "https://businessofcannabis.com/cannabis-news-today-monday-18-may-2026-rico-class-action-names-three-us-operators-as-canada-leads-germanys-medical-cannabis-imports/",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    source: "Business of Cannabis 5/18",
    featured: false,
  },
  {
    id: 82,
    title: "독일 1분기 의료대마 수입량 50톤 돌파 — 캐나다산이 53% 점유",
    summary: "2026년 1분기 독일의 의료대마 꽃 수입량이 총 50,539kg을 기록하며 전년 동기 대비 34% 성장했다. 캐나다 생산자들이 26,753kg을 공급하며 시장의 절반 이상을 점유했으며, 포르투갈(10톤)과 덴마크(3.3톤)가 뒤를 이었다. 독일 합법화 이후 캐나다 LP들의 유럽 수출이 더욱 가속화되고 있다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-05-18",
    country: "독일/캐나다",
    link: "https://businessofcannabis.com/cannabis-news-today-monday-18-may-2026-rico-class-action-names-three-us-operators-as-canada-leads-germanys-medical-cannabis-imports/",
    image: "https://images.unsplash.com/photo-1550831107-1553da8c8464?w=800&q=80",
    source: "Business of Cannabis 5/18",
    featured: false,
  },
  {
    id: 83,
    title: "UC 샌디에이고 연구: 청소년기 잦은 대마 사용, 인지 발달 저하와 연관성 확인",
    summary: "UC 샌디에이고 연구팀이 11,000명 이상의 아동을 7년간 추적 조사한 결과, 빈번한 대마 사용이 언어 기억, 학습 능력, 시공간 기술의 발달 지연과 밀접한 관련이 있음을 밝혀냈다. 이번 연구는 모발 검사를 통해 사용 빈도를 정확히 측정했으며, 향후 대마 규제 프레임워크의 연령 제한 논의에 중요한 근거가 될 전망이다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-05-18",
    country: "미국",
    link: "https://businessofcannabis.com/cannabis-news-today-monday-18-may-2026-rico-class-action-names-three-us-operators-as-canada-leads-germanys-medical-cannabis-imports/",
    image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&q=80",
    source: "Business of Cannabis 5/18",
    featured: false,
  },
];

const ARTICLES_20260608: Article[] = [
  {
    id: 93,
    title: "백악관 OMB, 의회에 헴프 CBD 합법 유지 촉구 — 광범위 금지법 수정 요청",
    summary: "백악관 예산관리국(OMB)이 의회에 헴프 유래 CBD 제품의 법적 정의를 업데이트해 미국인이 전스펙트럼 CBD 제품에 접근할 수 있게 하되, 심각한 건강 위험을 초래하는 제품은 제한하라고 촉구했다.",
    category: "policy",
    categoryLabel: "정책·규제",
    country: "미국",
    date: "2026-06-05",
    image: "https://images.unsplash.com/photo-1523995462485-3d171b5c8fa9?w=800&q=80",
    link: "https://www.marijuanamoment.net/white-house-pushes-congress-to-keep-hemp-cbd-products-legal-by-amending-broad-ban-thats-set-to-take-effect-later-this-year/",
    source: "Marijuana Moment 6/5",
    featured: false,
  },
  {
    id: 94,
    title: "INCB 비공개 서한: 'CBD는 국제 마약 조약 적용 대상 아니다'",
    summary: "국제마약통제위원회(INCB)가 비공개 서한에서 CBD는 국제 마약 조약의 적용을 받지 않으며, 비통제 카나비노이드 추출은 산업용 헴프 범주에 속한다고 밝혔다. 글로벌 CBD 산업에 중대한 법적 근거를 제공한다.",
    category: "global",
    categoryLabel: "글로벌",
    country: "국제",
    date: "2026-06-03",
    image: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800",
    link: "https://cannareporter.eu/en/2026/05/20/Exclusive-letter-from-INCB--kept-secret--reveals-that-CBD-is-outside-international-control./",
    source: "CannReporter EU 6/3",
    featured: false,
  },
  {
    id: 95,
    title: "Trulieve, NYSE 상장 — Schedule III 후 대마 기업 메이저 거래소 입성 가속",
    summary: "Trulieve Cannabis Corp.가 뉴욕증권거래소(NYSE)에서 거래를 시작했다. Schedule III 재분류 이후 대마 기업의 메이저 미국 거래소 입성이 가속화되고 있다.",
    category: "global",
    categoryLabel: "글로벌",
    country: "미국",
    date: "2026-06-05",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800",
    link: "https://www.prnewswire.com/news-releases/trulieve-announces-uplist-to-nyse-302792168.html",
    source: "PR Newswire 6/5",
    featured: false,
  },
  {
    id: 96,
    title: "헴프 기반 플라스틱, 친환경 포장재 대안으로 유망 — 신규 연구",
    summary: "신규 연구에서 헴프 기반 플라스틱이 전통 포장재의 환경 친화적 대안으로 유망함이 확인되었다. 산업용 헴프의 활용 범위가 식품·의약품을 넘어 소재 분야로 확대되고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    country: "미국",
    date: "2026-06-02",
    image: "https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=800",
    link: "https://www.marijuanamoment.net/hemp-based-plastic-shows-promise-as-environmentally-friendly-alternative-to-traditional-packaging-materials-study-finds/",
    source: "Marijuana Moment 6/2",
    featured: false,
  },
  {
    id: 97,
    title: "대마 성분, 교모세포종 등 암에 '일관된' 항종양 효과 — 과학 리뷰",
    summary: "과학 리뷰에서 대마 성분이 교모세포종(glioblastoma) 및 기타 암에서 일관된 항종양 효과를 보인다는 결과가 발표되었다. 대마 기반 항암 치료제 개발의 과학적 근거가 축적되고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    country: "미국",
    date: "2026-06-02",
    image: "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=800",
    link: "https://www.marijuanamoment.net/marijuana-components-have-consistent-anti-tumor-effects-in-glioblastoma-and-other-cancers-scientific-review-shows/",
    source: "Marijuana Moment 6/2",
    featured: false,
  },
];

const ARTICLES_20260615: Article[] = [
  {
    id: 98,
    title: "버지니아 주지사·의원, 이달 통과 가능 대마 판매 합법화 타협안 논의",
    summary: "버지니아 의원들과 Spanberger(D) 주지사가 이달 예산안의 일부로 통과될 수 있는 성인용 대마 판매 합법화에 대해 '매우 생산적인' 타협안을 논의했다. 주지사 측은 '결승선을 함께 넘기를 고대한다'고 밝혔다.",
    category: "policy",
    categoryLabel: "정책·규제",
    country: "미국",
    date: "2026-06-08",
    image: "https://images.unsplash.com/photo-1555848962-6e79363ec58f?w=800",
    link: "https://www.marijuanamoment.net/virginia-lawmakers-and-governor-meet-to-discuss-marijuana-sales-legalization-compromise-that-could-pass-this-month/",
    source: "Marijuana Moment 6/8",
    featured: false,
  },
  {
    id: 99,
    title: "뉴저지 주지사, 대형 헴프 음료 허용·의료 대마 약국 기호용 판매 추가 법안 서명",
    summary: "뉴저지 Sherrill(D) 주지사가 대용량 헴프 음료를 허용하고, 의료 대마 약국이 지역 승인 없이 기호용 판매를 추가할 수 있도록 하는 법안에 서명했다.",
    category: "policy",
    categoryLabel: "정책·규제",
    country: "미국",
    date: "2026-06-08",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800",
    link: "https://www.nj.gov/governor/news/2026/approved/20260529a.shtml",
    source: "NJ Governor 6/8",
    featured: false,
  },
  {
    id: 100,
    title: "의료 대마 추출물, 암환자 증상 '의미있게' 개선 — 환자 50%에서 수면·불안 호전",
    summary: "신규 연구에서 의료 대마 추출물이 환자 약 50%에서 암 관련 증상, 특히 수면 및 불안 증상에 의미있게 유익한 것으로 나타났다. THC·CBD·1:1 세 가지 추출물 모두 위약보다 유의하게 효과적이었다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    country: "미국",
    date: "2026-06-11",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800",
    link: "https://www.marijuanamoment.net/marijuana-extracts-meaningfully-improve-cancer-patients-symptoms-such-as-sleep-trouble-and-anxiety-study-shows/",
    source: "Marijuana Moment 6/11",
    featured: false,
  },
  {
    id: 101,
    title: "WNBA, 금지약물 목록에서 대마 제외 — 헴프 CBD 선수 보증 규칙 설정",
    summary: "WNBA가 금지약물 목록에서 대마를 제외하고 선수의 헴프 CBD 제품 보증에 대한 규칙을 설정했다. 프로 스포츠계의 대마 정책 변화를 상징하는 사례다.",
    category: "global",
    categoryLabel: "글로벌",
    country: "미국",
    date: "2026-06-11",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800",
    link: "https://www.marijuanamoment.net/wnba-removes-marijuana-from-banned-substances-list-and-sets-rules-for-player-endorsements-of-hemp-cbd-products/",
    source: "Marijuana Moment 6/11",
    featured: false,
  },
  {
    id: 102,
    title: "미주리, 5월 합법 대마 매출 $1.351억 — 사상 최대치 경신",
    summary: "미주리 소매업체들이 5월 합법 대마 제품 1억 3,510만 달러어치를 판매하며 사상 최대 기록을 경신했다. 합법화 2년 만에 연간 15억 달러 페이스에 도달했다.",
    category: "global",
    categoryLabel: "글로벌",
    country: "미국",
    date: "2026-06-11",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800",
    link: "https://mogreenway.com/2026/06/09/missouri-marijuana-sales-reach-record-highs-in-may/",
    source: "MO Greenway 6/9",
    featured: false,
  },
  {
    id: 103,
    title: "콜로라도 주지사, 이보가인 연구 파일럿 프로그램 신설 법안 서명",
    summary: "콜로라도 Polis(D) 주지사가 이보가인 연구 파일럿 프로그램을 신설하는 법안에 서명했다. 사이키델릭 기반 약물사용장애 치료 연구가 주 차원에서 공식화되었다.",
    category: "policy",
    categoryLabel: "정책·규제",
    country: "미국",
    date: "2026-06-10",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800",
    link: "https://governorsoffice.colorado.gov/governor/news/governor-polis-signs-bills-law-62",
    source: "CO Governor 6/10",
    featured: false,
  },
  {
    id: 104,
    title: "하원 세출위, 연방 공무원 산재보험 의료 대마 적용 차단 법안 승인",
    summary: "하원 세출위원회가 대마 분류 변경과 무관하게 연방 산재보험 프로그램의 의료 대마 적용을 차단하는 조항이 포함된 법안을 승인했다. 재분류의 실질적 한계를 보여주는 사례다.",
    category: "policy",
    categoryLabel: "정책·규제",
    country: "미국",
    date: "2026-06-11",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    link: "https://www.marijuanamoment.net/federal-employees-couldnt-get-medical-marijuana-covered-by-workers-comp-under-bill-advancing-in-congress/",
    source: "Marijuana Moment 6/11",
    featured: false,
  },
];

// ── 2026-06-22 주간 뉴스 ──────────────────────────────────────────────────

const ARTICLES_20260622: Article[] = [
  {
    id: 106,
    title: "美 연방대법원, 대마 사용자 총기 소지권 인정 — 만장일치로 정부 패소",
    summary: "미국 연방대법원이 만장일치로 대마 사용자의 총기 소지권을 인정하며 정부 측 패소 판결을 내렸다. 연방법상 대마 사용자의 총기 소지를 금지한 조항이 수정헌법 제2조에 위배된다는 취지로, 대마 관련 연방 규제의 헌법적 한계를 명확히 한 역사적 판결이다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-06-19",
    country: "미국",
    link: "https://www.marijuanamoment.net/supreme-court-unanimously-rules-for-marijuana-user-in-gun-rights-case/",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    source: "Marijuana Moment 6/19",
    featured: false,
  },
  {
    id: 107,
    title: "일리노이 Pritzker 주지사, 대마 종합 개정법 서명 — 소지한도 2배·헴프 THC 제한",
    summary: "일리노이 주지사가 대마 종합 개정법에 서명했다. 성인 소지 한도를 2배로 늘리고, 헴프 유래 THC 제품에 대한 규제를 강화하는 내용을 담고 있다. 합법화 이후 시장 성숙에 따른 규제 정비 사례로 주목된다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-06-15",
    country: "미국",
    link: "https://www.marijuanamoment.net/illinois-governor-signs-marijuana-omnibus-bill-doubling-possession-limits-and-restricting-hemp-thc/",
    image: "https://images.unsplash.com/photo-1555848962-6e79363ec58f?w=800&q=80",
    source: "Marijuana Moment 6/15",
    featured: false,
  },
  {
    id: 108,
    title: "우크라이나, 의료 대마 프로그램 공식 가동 — 첫 THC 제품 환자에 처방",
    summary: "우크라이나가 의료 대마 프로그램을 공식 가동하고 첫 THC 함유 제품을 환자에게 처방했다. 전쟁 중인 국가가 의료 대마를 도입한 이례적 사례로, 전쟁 부상자 및 PTSD 환자 치료 목적이 주요 배경으로 꼽힌다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-06-15",
    country: "우크라이나",
    link: "https://www.marijuanamoment.net/ukraine-officially-launches-medical-marijuana-program-dispensing-first-thc-products-to-patients/",
    image: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&q=80",
    source: "Marijuana Moment 6/15",
    featured: false,
  },
  {
    id: 109,
    title: "DEA, 대마 재분류 청문회에 '반대 측만' 초청 — 공정성 논란",
    summary: "DEA가 대마 Schedule III 재분류 관련 청문회 참가자를 선정하면서 재분류 반대 측 증인만 초청했다는 사실이 알려져 공정성 논란이 불거졌다. 재분류 지지 측은 절차적 편향을 강하게 비판하고 있다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-06-19",
    country: "미국",
    link: "https://www.marijuanamoment.net/dea-only-invited-opponents-of-marijuana-rescheduling-to-testify-at-hearing/",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    source: "Marijuana Moment 6/19",
    featured: false,
  },
  {
    id: 110,
    title: "약물검사 업계·제약사, 연방항소법원에 대마 재분류 차단 요청",
    summary: "약물검사 업계와 일부 제약사들이 DEA의 대마 Schedule III 재분류를 막기 위해 연방항소법원에 소송을 제기했다. 재분류가 자신들의 사업에 타격을 줄 것이라는 이유로, 재분류를 둘러싼 법적 공방이 본격화되고 있다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-06-12",
    country: "미국",
    link: "https://www.marijuanamoment.net/drug-testing-industry-and-pharma-company-ask-federal-appeals-court-to-block-marijuana-rescheduling/",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    source: "Marijuana Moment 6/12",
    featured: false,
  },
  {
    id: 111,
    title: "미국 주(州)들, 성인용 대마 누적 세수 $284억 돌파 — 일부 주는 주류 추월",
    summary: "Marijuana Policy Project(MPP) 신규 보고서에 따르면 미국 주들이 성인용 대마 판매로 누적 $284억(약 38조원)의 세수를 창출했다. 일부 주에서는 대마 세수가 주류 세수를 추월하기 시작했으며, 합법화의 재정적 효과가 가시화되고 있다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-06-19",
    country: "미국",
    link: "https://www.marijuanamoment.net/legal-marijuana-states-have-now-collected-28-4-billion-in-tax-revenue/",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    source: "Marijuana Moment 6/19",
    featured: false,
  },
  {
    id: 112,
    title: "미국 2025년 합법 대마 매출 사상 첫 감소 — 가격 압축·공급 과잉 원인",
    summary: "Vangst·Whitney Economics 보고서에 따르면 미국 합법 대마 시장이 2025년 사상 처음으로 매출 감소를 기록했다. 가격 압축과 공급 과잉이 주요 원인으로 지목됐으며, 시장 성숙에 따른 구조 재편이 본격화되고 있다는 분석이다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-06-19",
    country: "미국",
    link: "https://www.marijuanamoment.net/legal-marijuana-sales-declined-for-first-time-ever-in-2025-report/",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    source: "Marijuana Moment 6/19",
    featured: false,
  },
  {
    id: 113,
    title: "CBD, 척수손상 신경병증 통증 강도 유의미하게 감소 — The Lancet 게재",
    summary: "척수손상 환자를 대상으로 한 임상 연구에서 CBD가 신경병증 통증 강도를 유의미하게 감소시키고 전반적으로 내약성이 좋았다는 결과가 나왔다. 해당 연구는 의학 분야 최고 권위 학술지 The Lancet eClinicalMedicine에 게재되어 CBD의 임상적 근거를 한층 강화했다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-06-16",
    country: "미국",
    link: "https://www.thelancet.com/journals/eclinm/article/PIIS2589-5370(26)00234-8/fulltext",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
    source: "The Lancet 6/16",
    featured: false,
  },
  {
    id: 114,
    title: "대마 수면 효과, THC보다 CBD·CBN이 핵심 — USF 간호대 연구",
    summary: "University of South Florida 간호대 연구진의 신규 연구에 따르면 대마의 수면 개선 효과에서 가장 강력한 근거는 CBD와 CBN, 그리고 둘의 조합과 연관되어 있으며, 주로 THC가 아닌 것으로 나타났다. 수면 분야에서 비(非)THC 카나비노이드의 중요성이 부각되고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-06-16",
    country: "미국",
    link: "https://www.marijuanamoment.net/our-new-study-shows-that-the-science-of-cannabis-and-sleep-extends-beyond-thc-op-ed/",
    image: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&q=80",
    source: "Marijuana Moment 6/16",
    featured: false,
  },
  {
    id: 115,
    title: "대마 기반 의약품, 과가동성 만성 통증 환자에 지속적 개선 효과 확인",
    summary: "연구에 따르면 대마 기반 의약품 치료가 과가동성(hypermobility) 관련 만성 통증 환자의 증상에 지속적인 개선 효과와 연관되는 것으로 나타났다. 기존 진통제에 반응하지 않는 난치성 통증 환자군에서의 가능성을 제시한 연구로 주목받고 있다.",
    category: "rnd",
    categoryLabel: "R&D·기술",
    date: "2026-06-15",
    country: "미국",
    link: "https://link.springer.com/article/10.1007/s10067-026-08166-z",
    image: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=800&q=80",
    source: "Springer 6/15",
    featured: false,
  },
  {
    id: 116,
    title: "인도 히마찰프라데시주 내각, 산업용 헴프·의료용 대마 재배 합법화 승인",
    summary: "인도 히마찰프라데시주 내각이 산업용 헴프와 의료용 대마 재배를 합법화하는 제안을 승인했다. 히말라야 산악 지대에 위치한 이 주는 전통적으로 대마 재배가 성행했던 지역으로, 이번 합법화로 농민들이 고부가가치 작물에 합법적으로 접근할 수 있게 됐다. 아시아 최대 민주주의 국가인 인도에서 주(州) 차원의 대마 합법화 움직임이 본격화되고 있다는 점에서 주목된다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-06-22",
    country: "인도",
    link: "https://www.aninews.in/news/national/general-news/himachal-cabinet-approves-regulated-cannabis-farming-farmers-to-benefit-from-high-value-crop-jagat-singh-negi20260620225532/",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    source: "ANI 6/22",
    featured: false,
  },
  {
    id: 117,
    title: "아일랜드 의회 마약사용위원회, 모든 마약 비범죄화 권고",
    summary: "아일랜드 입법부의 마약사용 합동위원회(Joint Committee on Drugs Use)가 대마를 포함한 모든 마약의 비범죄화를 권고했다. 유럽에서 포르투갈의 전면 비범죄화 모델을 따르는 국가가 늘어나는 가운데, 아일랜드 의회 차원의 공식 권고가 나온 것은 이례적이다. 실제 입법으로 이어질지는 미지수이나, 유럽 대마 정책 흐름의 변화를 보여주는 상징적 사례로 평가된다.",
    category: "global",
    categoryLabel: "글로벌",
    date: "2026-06-25",
    country: "아일랜드",
    link: "https://www.rte.ie/news/politics/2026/0624/1580028-drugs-committee/",
    image: "https://images.unsplash.com/photo-1590089415225-401ed6f9db8e?w=800&q=80",
    source: "RTE 6/25",
    featured: false,
  },
];

// ── 2026-06-29 주간 뉴스 ──────────────────────────────────────────────────

const ARTICLES_20260629: Article[] = [
  {
    id: 118,
    title: "백악관, 의회에 '헴프 공정 대우' 촉구 — 11월 재범죄화법 최소 연기 요청",
    summary: "백악관이 의회에 서한을 보내 11월 발효 예정인 광범위한 헴프 재범죄화법을 '최소한' 연기해 '헴프 제품의 공정한 대우를 보장'하라고 촉구했다. THC 제품을 합법 유지하되 규제를 추가하는 최근 수정안을 인용하며, 업계의 법적 불확실성 해소를 위한 유예 기간이 필요하다는 입장을 밝혔다. 이미 속보 배너에 등록된 OMB 촉구 서한의 후속 조치로, 행정부 차원의 헴프 보호 의지가 재확인됐다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-06-25",
    country: "미국",
    link: "https://www.marijuanamoment.net/white-house-pushes-congress-to-ensure-fair-treatment-of-hemp-products-by-calling-off-broad-recriminalization-law-set-for-november/",
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
    source: "Marijuana Moment 6/25",
    featured: false,
  },
  {
    id: 119,
    title: "DEA 재분류 청문회 첫날: DEA·FDA '대마가 알코올·오피오이드보다 안전' 증언 부각",
    summary: "DEA와 FDA 측 변호인이 대마 재분류 청문회 첫날 대마의 의학적 효용과 알코올·오피오이드 대비 상대적 안전성에 관한 증언을 부각했다. 초당파 의원들은 의회의 재분류 차단 시도가 성공하지 못할 것이라 전망했다. 이번 청문회는 미국 대마 정책 역사상 가장 중요한 공개 심리 중 하나로, DEA의 Schedule III 재분류 절차가 사실상 돌이킬 수 없는 단계에 접어들었다는 평가가 나온다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-06-30",
    country: "미국",
    link: "https://www.marijuanamoment.net/dea-and-fda-highlight-how-marijuana-is-safer-than-alcohol-and-opioids-during-rescheduling-hearings-opening-day/",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80",
    source: "Marijuana Moment 6/30",
    featured: false,
  },
  {
    id: 120,
    title: "버지니아, 성인용 대마 판매 합법화 최종 통과 — 예산안에 포함되어 정식 발효",
    summary: "버지니아 상·하원이 Spanberger(D) 주지사의 예산안 수정안을 수용하면서 성인용 대마 판매 합법화가 최종 확정됐다. 주지사의 추가 조치 없이 법률로 정식 발효되며 수년간의 법적 공백이 종료됐다. 앞서 주지사가 독립 법안에 거부권을 행사한 바 있으나, 예산안에 포함시키는 우회 전략으로 합법화가 성사됐다. 버지니아는 미국 동부 주요 주 중 성인용 대마 판매를 합법화한 최신 사례가 됐다.",
    category: "policy",
    categoryLabel: "정책·규제",
    date: "2026-06-30",
    country: "미국",
    link: "https://www.marijuanamoment.net/virginia-lawmakers-give-final-approval-to-marijuana-sales-legalization-as-part-of-budget/",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    source: "Marijuana Moment 6/30",
    featured: false,
  },
];

// ── 입법동향 데이터 ──────────────────────────────────────────────────────

export type LegislationStatus = "접수" | "위원회 심사" | "체계자구 심사" | "본회의 심의" | "정부이송" | "공포";

export interface Legislation {
  id: number;
  billNo: string;
  title: string;
  proposer: string;
  proposerCount: number;
  committee: string;
  proposedDate: string;
  status: LegislationStatus;
  summary: string;
  keyPoints: string[];
  link: string;
  tags: string[];
}

export const LEGISLATIONS: Legislation[] = [
  {
    id: 1,
    billNo: "2217773",
    title: "마약류 관리에 관한 법률 일부개정법률안",
    proposer: "서미화의원",
    proposerCount: 10,
    committee: "보건복지위원회",
    proposedDate: "2026-03-26",
    status: "위원회 심사",
    summary: "CBD 등 의료적 효용성이 있는 대마 성분을 향정신성의약품으로 분류하여 국내 제조·품목허가를 허용하고, 의료용 목적 대마 재배자 허가 제도를 신설하는 법안. 대법원 판례(2022두60776)에 따라 대마 정의를 명확히 하고, 의료용 마약류 원료 관리 지원센터 지정 근거를 마련한다.",
    keyPoints: [
      "CBD 등 대마 성분을 향정신성의약품으로 분류 → 국내 의약품 제조·품목허가 가능",
      "의료용 목적 대마 재배자 정의 확대 및 식약처 허가 절차 신설",
      "의료용 마약류 원료 관리 지원센터 지정 (전담기관)",
      "대법원 판례 반영: CBD도 대마 정의에 포함 명확화",
    ],
    link: "https://likms.assembly.go.kr/bill/bi/billDetailPage.do?billId=PRC_B2Z6Y0G3H2F0E0D9Z5A7Y4X0V7M3N8",
    tags: ["CBD", "의료대마", "마약류관리법", "국내제조"],
  },
  {
    id: 2,
    billNo: "2217027",
    title: "헴프산업 육성 및 헴프 안전관리에 관한 특별법안",
    proposer: "윤준병의원",
    proposerCount: 11,
    committee: "농림축산식품해양수산위원회",
    proposedDate: "2026-02-25",
    status: "위원회 심사",
    summary: "유해성분(THC) 농도가 낙은 대마를 '험프'로 명확히 정의하고, 헴프의 재배·가공·유통·판매 전 과정에 대한 안전관리 체계를 마련하는 헴프 전용 특별법. 의료·식품·산업용 등 다양한 분야에서의 헴프 활용 근거를 마련하고, 헴프산업진흥원 설립 및 헴프산업 클러스터 지정 등 산업 진흥 인프라를 구축한다.",
    keyPoints: [
      "'\ud5d8\ud504' 정의 신설 — THC 농도 기준 이하 대마를 마약류와 구분하여 별도 관리",
      "헴프 재배·육종·제조·판매업 허가제 도입 (농식품부·식약처 이중 허가)",
      "헴프산업진흥원 설립 및 5년 단위 종합계획 수립",
      "헴프산업 클러스터 지정 제도 도입 (시·도지사 신청)",
      "헴프 추적관리시스템 구축·운영 (식약처 주관)",
    ],
    link: "https://likms.assembly.go.kr/bill/bi/billDetailPage.do?billId=PRC_L2J6K0G2G1F2D1E3C1C2L0L2J1I8I8",
    tags: ["헴프", "헴프특별법", "산업육성", "재배허가", "헴프산업진흥원"],
  },
  {
    id: 3,
    billNo: "2219769",
    title: "마약류 관리에 관한 법률 일부개정법률안",
    proposer: "김형동의원",
    proposerCount: 13,
    committee: "미확정",
    proposedDate: "2026-07-06",
    status: "접수",
    summary: "CBD 등 의료적 효용성이 있는 대마 성분을 향정신성의약품으로 분류하여 국내 제조를 허용하고, 의료용 대마 재배자 허가 제도를 신설하는 법안. 국가 주도의 의료용 마약류 원료관리센터를 설립하여 재배부터 추출·제조·원료 배정까지 엄격히 관리하는 체계를 구축한다.",
    keyPoints: [
      "CBD 등 대마 성분을 향정신성의약품으로 분류 → 국내 의약품 제조·품목허가 가능",
      "의료용 목적 대마 재배자 허가 제도 신설 (식약처 허가)",
      "의료용 마약류 원료관리센터 설립 (국가 주도 공급망 구축)",
      "재배 단계부터 추출·정제·제조·원료 배정까지 국가 주도 관리 체계",
    ],
    link: "https://likms.assembly.go.kr/bill/bi/billDetailPage.do?billId=PRC_O2N6C0Z5M2J2I0F9N5M4L2K6R6P3L9",
    tags: ["CBD", "의료대마", "마약류관리법", "국내제조", "원료관리센터"],
  },
  {
    id: 4,
    billNo: "2219780",
    title: "마약류 관리에 관한 법률 일부개정법률안",
    proposer: "신성범의원",
    proposerCount: 10,
    committee: "미확정",
    proposedDate: "2026-07-06",
    status: "접수",
    summary: "THC 함유량이 건조 중량 기준 0.3% 이하인 헴프(Cannabis sativa L)를 대마의 범위에서 완전 제외하여 의료용은 물론 기능성 식품·화장품·섬유·사료 등 다양한 산업 분야에서 합법적으로 활용할 수 있도록 하는 법안. WHO 권고와 UN 마약위원회의 대마 고위험 마약류 제외 결정을 반영하며, 경북 헴프 규제자유특구에서 확인된 산업화 가능성을 전국적으로 확대하는 것이 핵심이다.",
    keyPoints: [
      "THC 0.3% 이하 헴프를 대마 범위에서 완전 제외 (마약류관리법 제2조 개정)",
      "의료용·기능성 식품·화장품·섬유·사료 등 전 산업 분야 합법 활용 가능",
      "WHO 권고 및 UN 마약위원회 결정 국내법 반영",
      "경북 헴프 규제자유특구 성과를 전국 제도화로 확대",
    ],
    link: "https://likms.assembly.go.kr/bill/bi/billDetailPage.do?billId=PRC_J2K6J0H7X0Y3W1E3D3E0D2B0J8I2J3",
    tags: ["헴프", "THC0.3%", "마약류관리법", "대마제외", "산업화"],
  },
];

export const ARTICLES: Article[] = [
  ...ARTICLES_DOMESTIC,
  ...ARTICLES_20260629,
  ...ARTICLES_20260622,
  ...ARTICLES_20260615,
  ...ARTICLES_20260608,
  ...ARTICLES_20260525,
  ...ARTICLES_20260518,
  ...ARTICLES_20260511,
  ...ARTICLES_20260504,
].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

export const BREAKING_NEWS = [
  {
    text: "국내 속보: 신성범 의원, 'THC 0.3% 이하 헴프 대마 제외' 마약류관리법 개정안 대표발의 — 전 산업 활용 기반 마련",
    link: "/domestic/123",
  },
  {
    text: "국내 속보: 국회 '대마 성분 의약품 도입' 정책 토론회 — 서미화·김형동 의원·식약처 공동 개최, CBD 국내 생산 공론화",
    link: "/domestic/122",
  },
  {
    text: "국내 속보: CBD 국내 제조 허용 법안 2건 동시 발의 — 여야 의원 공동 추진",
    link: "/legislation",
  },
  {
    text: "속보: INCB 비공개 서한 — 'CBD는 국제 마약 조약 적용 대상 아니다'",
    link: "/global/94",
  },
  {
    text: "속보: Trulieve, NYSE 상장 — Schedule III 후 대마 기업 메이저 거래소 입성 가속",
    link: "/global/95",
  },
  {
    text: "속보: 백악관 OMB, 의회에 헴프 CBD 합법 유지 촉구 — 광범위 금지법 수정 요청",
    link: "/policy/93",
  },
  {
    text: "속보: 의료 대마 추출물, 암환자 증상 '의미있게' 개선 — 환자 50% 호전",
    link: "/rnd/100",
  },
  {
    text: "속보: 미주리, 5월 합법 대마 매출 $1.351억 — 사상 최대치 경신",
    link: "/global/102",
  },
  {
    text: "국내 속보: HLB생명과학R&D, 경북 헴프 규제자유특구 참여 — CBG·CBC 등 미량 칸나비노이드 신약 296억 투자",
    link: "/domestic/121",
  },
  {
    text: "속보: 버지니아, 성인용 대마 판매 합법화 최종 통과 — 예산안 포함 정식 발효",
    link: "/policy/120",
  },
  {
    text: "속보: DEA 재분류 청문회 개시 — DEA·FDA '대마가 알코올·오피오이드보다 안전' 증언",
    link: "/policy/119",
  },
];
